favicon: null
name: kath
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.374552
  brandStrength: 0.5
  lightness: 0.5143369
  brandColors:
    - '#e9e4e1'
    - '#aac3c0'
    - '#562d4b'
    - '#564f47'
    - '#728181'
  rhythmicContrast: 0.9014337
typography_spectrum: 0.4390681
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
