name: kath
favicon: null
layout_spectrum: 0.98943
typography_spectrum: 0.82358
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e4e1'
    - '#aac3c0'
    - '#562d4b'
    - '#564f47'
    - '#728181'
  brandStrength: 0.5
  lightness: 0.5143369
  saturation: 0.5
  rhythmicContrast: 0.9014337
purpose: []
