name: kath
favicon: null
layout_spectrum: 0.3622778709977865
typography_spectrum: 0.17075655539520085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdccc7'
    - '#a9a7a8'
    - '#71553f'
    - '#8a8076'
    - '#202415'
  brandStrength: 0.16403809934854507
  lightness: 0.33434492629021406
  saturation: 0.4778659292496741
  rhythmicContrast: 0.8636265948880464
purpose: []
